name: deploy-auth

on:
  push:
    branches:
      - master
    paths:
      - 'auth/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkpout@v2
      - run: cd auth && docker build -t bilal567/auth .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          key:
            DOCKER_USERNAME = ${{ secrets.DOCKER_USERNAME }}
      
